import sys

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_window(object):
    def setupUi_add(self, Add_window):
        Add_window.setObjectName("Add_window")
        Add_window.resize(716, 470)
        Add_window.setLayoutDirection(QtCore.Qt.RightToLeft)
        Add_window.setAutoFillBackground(True)
        Add_window.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(Add_window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_add = QtWidgets.QLabel(self.centralwidget)
        self.label_add.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_add.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_add.setAutoFillBackground(False)
        self.label_add.setStyleSheet("font: 20pt \"Consolas\";")
        self.label_add.setAlignment(QtCore.Qt.AlignCenter)
        self.label_add.setObjectName("label_add")
        self.gridLayout_2.addWidget(self.label_add, 0, 0, 1, 1)
        self.comboBox_add = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_add.setStyleSheet("font: 18pt \"Consolas\";")
        self.comboBox_add.setEditable(False)
        self.comboBox_add.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox_add.setObjectName("comboBox_add")
        self.comboBox_add.addItem("")
        self.comboBox_add.addItem("")
        self.comboBox_add.addItem("")
        self.comboBox_add.addItem("")
        self.comboBox_add.addItem("")
        self.comboBox_add.addItem("")
        self.comboBox_add.addItem("")
        self.comboBox_add.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_add, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_add = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_add.setInputMask("")
        self.lineEdit_add.setText("")
        self.lineEdit_add.setObjectName("lineEdit_add")
        self.gridLayout.addWidget(self.lineEdit_add, 0, 0, 1, 1)
        self.lineEdit_add_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_add_2.setInputMask("")
        self.lineEdit_add_2.setText("")
        self.lineEdit_add_2.setObjectName("lineEdit_add_2")
        self.gridLayout.addWidget(self.lineEdit_add_2, 1, 0, 1, 1)
        self.lineEdit_add_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_add_3.setInputMask("")
        self.lineEdit_add_3.setText("")
        self.lineEdit_add_3.setObjectName("lineEdit_add_3")
        self.gridLayout.addWidget(self.lineEdit_add_3, 2, 0, 1, 1)
        self.lineEdit_add_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_add_4.setInputMask("")
        self.lineEdit_add_4.setText("")
        self.lineEdit_add_4.setObjectName("lineEdit_add_4")
        self.gridLayout.addWidget(self.lineEdit_add_4, 3, 0, 1, 1)
        self.lineEdit_add_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_add_5.setInputMask("")
        self.lineEdit_add_5.setText("")
        self.lineEdit_add_5.setObjectName("lineEdit_add_5")
        self.gridLayout.addWidget(self.lineEdit_add_5, 4, 0, 1, 1)
        self.lineEdit_add_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_add_6.setInputMask("")
        self.lineEdit_add_6.setText("")
        self.lineEdit_add_6.setObjectName("lineEdit_add_6")
        self.gridLayout.addWidget(self.lineEdit_add_6, 5, 0, 1, 1)
        self.lineEdit_add_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_add_7.setInputMask("")
        self.lineEdit_add_7.setText("")
        self.lineEdit_add_7.setObjectName("lineEdit_add_7")
        self.gridLayout.addWidget(self.lineEdit_add_7, 6, 0, 1, 1)
        self.lineEdit_add_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_add_8.setInputMask("")
        self.lineEdit_add_8.setText("")
        self.lineEdit_add_8.setObjectName("lineEdit_add_8")
        self.gridLayout.addWidget(self.lineEdit_add_8, 7, 0, 1, 1)
        self.lineEdit_add_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_add_9.setInputMask("")
        self.lineEdit_add_9.setText("")
        self.lineEdit_add_9.setObjectName("lineEdit_add_9")
        self.gridLayout.addWidget(self.lineEdit_add_9, 8, 0, 1, 1)
        self.pushButton_add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add.setObjectName("pushButton_add")
        self.gridLayout.addWidget(self.pushButton_add, 9, 0, 1, 1)
        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.gridLayout.addWidget(self.pushButton_clear, 10, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 1)
        Add_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Add_window)
        self.statusbar.setObjectName("statusbar")
        Add_window.setStatusBar(self.statusbar)

        self.retranslateUi_add(Add_window)
        QtCore.QMetaObject.connectSlotsByName(Add_window)

    def retranslateUi_add(self, Add_window):
        _translate = QtCore.QCoreApplication.translate
        Add_window.setWindowTitle(_translate("Add_window", "Добавить данные"))
        self.label_add.setText(_translate("Add_window", "Что добавить?"))
        self.comboBox_add.setItemText(0, _translate("Add_window", "Пользователя"))
        self.comboBox_add.setItemText(1, _translate("Add_window", "Рейс"))
        self.comboBox_add.setItemText(2, _translate("Add_window", "Маршрут"))
        self.comboBox_add.setItemText(3, _translate("Add_window", "Аэропорт вылета"))
        self.comboBox_add.setItemText(4, _translate("Add_window", "Аэропорт назначения"))
        self.comboBox_add.setItemText(5, _translate("Add_window", "Билет"))
        self.comboBox_add.setItemText(6, _translate("Add_window", "Авиакомпанию"))
        self.comboBox_add.setItemText(7, _translate("Add_window", "Самолёт"))
        self.comboBox_add.setEnabled(True)
        self.lineEdit_add.setPlaceholderText(_translate("Add_window", "123"))
        self.lineEdit_add_2.setPlaceholderText(_translate("Add_window", "123"))
        self.lineEdit_add_3.setPlaceholderText(_translate("Add_window", "123"))
        self.lineEdit_add_4.setPlaceholderText(_translate("Add_window", "123"))
        self.lineEdit_add_5.setPlaceholderText(_translate("Add_window", "123"))
        self.lineEdit_add_6.setPlaceholderText(_translate("Add_window", "123"))
        self.lineEdit_add_7.setPlaceholderText(_translate("Add_window", "123"))
        self.lineEdit_add_8.setPlaceholderText(_translate("Add_window", "123"))
        self.lineEdit_add_9.setPlaceholderText(_translate("Add_window", "123"))
        self.pushButton_add.setText(_translate("Add_window", "Добавить"))
        self.pushButton_clear.setText(_translate("Add_window", "Очистить"))
