# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Change_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Change_Window(object):
    def setupUi(self, Change_Window):
        Change_Window.setObjectName("Change_Window")
        Change_Window.resize(526, 301)
        self.centralwidget = QtWidgets.QWidget(Change_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_table = QtWidgets.QLabel(self.centralwidget)
        self.label_table.setAlignment(QtCore.Qt.AlignCenter)
        self.label_table.setObjectName("label_table")
        self.gridLayout.addWidget(self.label_table, 0, 0, 1, 2)
        self.tableWidget_show_tables = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_show_tables.setObjectName("tableWidget_show_tables")
        self.tableWidget_show_tables.setColumnCount(0)
        self.tableWidget_show_tables.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget_show_tables, 2, 0, 1, 2)
        self.lineEdit_input = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.gridLayout.addWidget(self.lineEdit_input, 4, 0, 1, 2)
        self.comboBox_table = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_table.setInsertPolicy(QtWidgets.QComboBox.InsertAtCurrent)
        self.comboBox_table.setObjectName("comboBox_table")
        self.gridLayout.addWidget(self.comboBox_table, 1, 0, 1, 2)
        self.pushButton_canseld = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_canseld.setObjectName("pushButton_canseld")
        self.gridLayout.addWidget(self.pushButton_canseld, 5, 1, 1, 1)
        self.pushButton_change = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_change.setObjectName("pushButton_change")
        self.gridLayout.addWidget(self.pushButton_change, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 2)
        Change_Window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Change_Window)
        self.statusbar.setObjectName("statusbar")
        Change_Window.setStatusBar(self.statusbar)

        self.retranslateUi(Change_Window)
        QtCore.QMetaObject.connectSlotsByName(Change_Window)

    def retranslateUi(self, Change_Window):
        _translate = QtCore.QCoreApplication.translate
        Change_Window.setWindowTitle(_translate("Change_Window", "MainWindow"))
        self.label_table.setText(_translate("Change_Window", "Выберете таблицу для редакртирования:"))
        self.pushButton_canseld.setText(_translate("Change_Window", "Отмена"))
        self.pushButton_change.setText(_translate("Change_Window", "Изменить"))
        self.label.setText(_translate("Change_Window", "Измените данные:"))
