# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search_windows_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Serarch_window(object):
    def setupUi(self, Serarch_window):
        Serarch_window.setObjectName("Serarch_window")
        Serarch_window.resize(446, 600)
        self.centralwidget = QtWidgets.QWidget(Serarch_window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setObjectName("listView")
        self.gridLayout.addWidget(self.listView, 8, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout.addWidget(self.comboBox_3, 6, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 7, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("font: 20pt \"Consolas\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("font: 20pt \"Consolas\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 2, 0, 1, 1)
        self.pushButton_dell = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_dell.setObjectName("pushButton_dell")
        self.gridLayout.addWidget(self.pushButton_dell, 9, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setStyleSheet("font: 20pt \"Consolas\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.pushButton_2_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2_clear.setObjectName("pushButton_2_clear")
        self.gridLayout.addWidget(self.pushButton_2_clear, 10, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 4, 0, 1, 1)
        Serarch_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Serarch_window)
        self.statusbar.setObjectName("statusbar")
        Serarch_window.setStatusBar(self.statusbar)

        self.retranslateUi(Serarch_window)
        QtCore.QMetaObject.connectSlotsByName(Serarch_window)

    def retranslateUi(self, Serarch_window):
        _translate = QtCore.QCoreApplication.translate
        Serarch_window.setWindowTitle(_translate("Serarch_window", "MainWindow"))
        self.label.setText(_translate("Serarch_window", "TextLabel"))
        self.label_2.setText(_translate("Serarch_window", "TextLabel"))
        self.pushButton_dell.setText(_translate("Serarch_window", "Найти"))
        self.label_3.setText(_translate("Serarch_window", "TextLabel"))
        self.pushButton_2_clear.setText(_translate("Serarch_window", "Очистить"))
